[tool.poetry]
name = "mlops-platform-kserve-template"
version = "0.1.0"
description = ""
authors = [
    "Andres Cardoso Cordero <andres.cardoso@eviden.com>"
]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
kserve = "0.11.*"
joblib = "1.3.*"
minio = "7.2.*"
<<<<<<< HEAD
scikit-learn = "1.3.2" # was 1.4.0 (match requirements.txt)
numpy = "1.24.3"  # was 1.26.* (match requirements.txt)
beautifulsoup4 = "4.12.*"
requests = "^2.31"        # Added requests

# Added to match requirements.txt
pandas = "2.0.3"
matplotlib = "3.7.5"
scipy = "1.10.1"
#torch = "2.2.2"
tensorflow = "2.13.1"
#ipykernel = "6.29.5"
#jupyterlab = "4.3.3"
#ipywidgets = "8.1.7"
h5py = "^3.14.0"

=======
scikit-learn = "1.4.0"
numpy = "1.26.*"
beautifulsoup4 = "4.12.*"
requests = "^2.31"        # Added requests

>>>>>>> origin/main
[tool.poetry.dev-dependencies]
pytest = "^7.4"
pytest-mock = "^3.11"

[tool.black]
line-length = 120
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
profile = "black"
py_version = 310
line_length = 120

[tool.poetry.scripts]
PYTHONDONTWRITEBYTECODE = "1"
