apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    sidecar.istio.io/inject: "true"
  name: zone-density-model
  namespace: models
  labels:
    name: zone-density-model-prediction
spec:
  predictor:
    maxReplicas: 1
    containers:
      - name: kserve-container
        image: ghcr.io/emeralds-horizon/zone-density-model:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
        env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: model-secrets-zone-density-model
                key: MINIO_ACCESS_KEY
          - name: MINIO_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: model-secrets-zone-density-model
                key: MINIO_SECRET_ACCESS_KEY
          - name: MINIO_API_URL
            valueFrom:
              secretKeyRef:
                name: model-secrets-zone-density-model
                key: MINIO_API_URL
          - name: MINIO_BUCKET
            valueFrom:
              secretKeyRef:
                name: model-secrets-zone-density-model
                key: MINIO_BUCKET
          - name: MODEL_PATH
            valueFrom:
              secretKeyRef:
                name: model-secrets-zone-density-model
                key: MODEL_PATH
    imagePullSecrets:
        - name: github-container-registry
